spring.application.name=spring

spring.datasource.url=jdbc:mysql://localhost:3306/bolao?useSSL=false&serverTimezone=America/Sao_Paulo&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=b9K8x2Yt4P1v5M9w3Z7n6X2c8L0q4F1j